server:
    port: 8088
spring:
    datasource:
        url: jdbc:sqlserver://localhost:1433;encrypt=false;databaseName=MockProject
        username: sa
        password: 123456789
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    jackson:
        time-zone: Asia/Ho_Chi_Minh
    mail:
        host: smtp.gmail.com
        port: 587
        username: kietmnvps27065@fpt.edu.vn
        password: rvgn lriz tjmu wcid
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
                    ssl.trust: smtp.gmail.com
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 67753201897-divbrclj6doajcepcsk4mp49g04lq54q.apps.googleusercontent.com
                        client-secret: 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
reset:
    token:
        expiry:
            minutes: 120
api:
    prefix: api/v1
